repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        fail_fast: true
      - id: check-merge-conflict
        fail_fast: true
      - id: detect-private-key
        fail_fast: true
  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
      - id: sync-pre-commit-deps
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/jakub-borusewicz/cue-auto-export
    rev: v1.1.2
    hooks:
      - id: cue-auto-export
        exclude: (?x)^(config/.* | cue.mod/.*)$
  - repo: local
    hooks:
      - id: update-cue-files
        name: update-cue-files
        entry: cue fix
        language: system
        pass_filenames: true
      - id: format-cue-files
        name: format-cue-files
        entry: cue fmt
        language: system
        pass_filenames: true
        files: .*\.cue$
      - id: cue-auto-export-tool
        name: cue-auto-export-tool
        entry: bash -c 'for f in "$@"; do cue cmd cue_auto_export -t pre_commit_input="$f"; done' --
#        entry: xargs -I {} cue cmd cue_auto_export -t pre_commit_input="{}"
#        entry: cue cmd cue_auto_export -t pre_commit_input="lol"
        language: system
        pass_filenames: true
        files: .*\.cue$
        exclude: (?x)^(config/.* | cue.mod/.* | project_tool.cue)$
